jbpm-designer-backend/src/main/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnit.java
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1093075
=> Corrected NPE when WID has no icon entry.

jbpm-designer-standalone/pom.xml, jbpm-designer-standalone/src/main/resources/org/jbpm/designer/jBPMDesigner.gwt.xml
Dependency updates for datamodeller
=> JBPM-4625 Generation of JPA enabled models

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/resource/JBPMBpmn2ResourceFactoryImpl.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/repository/Repository.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/server/Repository.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/server/diagram/Diagram.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/server/diagram/DiagramBuilder.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/server/diagram/JSONBuilder.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/server/diagram/Shape.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/plugin/IDiagramPluginFactory.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/preference/IDiagramPreferenceService.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/repository/IUUIDBasedRepository.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/repository/IUUIDBasedRepositoryService.java
* removed empty @return tags
* fixed some method param names
=> Fix Javadoc warnings

jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/VFSFileSystemProducer.java
Behavior of the tests is still the same, but following error messages were eliminated:
```2015-09-21 18:34:12,495 [main] ERROR Failed to register filesystem git://designer-playground14 with DEFAULT_FS_TYPE. Returning null.
20:34:14 org.uberfire.java.nio.file.FileSystemNotFoundException: No filesystem for uri (git://designer-playground14) found.
20:34:14 	at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.getFileSystem(JGitFileSystemProvider.java:669) ~[uberfire-nio2-jgit-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
20:34:14 	at org.uberfire.java.nio.file.FileSystems.getFileSystem(FileSystems.java:66) ~[uberfire-nio2-api-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
20:34:14 	at org.uberfire.io.impl.AbstractIOService.getFileSystem(AbstractIOService.java:220) …
```
=> backend tests: avoid confusing ERROR messages coming from UF

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxChecker.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/SyntaxCheckerServlet.java
Removed unused private attributes of BPMN2SyntaxChecker
=> removed unused attributes

.gitignore, org.jbpm/jbpm-designer-api/.zanata-cache/etag-cache.xml, org.jbpm/jbpm-designer-client/.zanata-cache/etag-cache.xml, org.jbpm/jbpm-designer-standalone/.zanata-cache/etag-cache.xml
(cherry picked from commit 10f1111f33bf6b33775edac7caa0ae6cc1f68e17)
=> added to .gitignore directory created by Zanata

pom.xml
1.8.0 is inherited from parents.
=> Minimal JDK version is 1.8

jbpm-designer-standalone/src/main/java/org/jbpm/designer/uberfire/backend/server/impl/LuceneConfigProducer.java
See also: 
- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/169
- https://github.com/uberfire/uberfire/pull/337
- https://github.com/uberfire/uberfire-extensions/pull/258
- https://github.com/droolsjbpm/kie-wb-common/pull/337
- https://github.com/droolsjbpm/jbpm-designer/pull/220
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/46
- https://github.com/droolsjbpm/jbpm-console-ng/pull/395
- https://github.com/droolsjbpm/drools-wb/pull/156
- https://github.com/droolsjbpm/kie-wb-distributions/pull/261
=> UF-295 - Upgrading lucene to 5.3.1

jbpm-designer-backend/pom.xml, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/TransformerServlet.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/TransformerServletTest.java, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/documentation/docstructure.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/processdoc/default.jsp
6.4.x PR for this Jira
parent poms need to resolve before depends build
=> JBPM-4979 - Generated PDF is unreadable

jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Core/main.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/saveplugin.js, jbpm-designer-client/src/test/java/org/jbpm/designer/client/DesignerPresenterTest.java
Commit cherry-picked from master to 6.4.x branch
=> BZ1269969: Fix restore BP functionality (#232)

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxChecker.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/SyntaxCheckerErrors.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxCheckerTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/exclusiveGatewayInproperProbabilities.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/exclusiveGatewayInvalidDefaultGate.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/exclusiveGatewayProperProbabilities.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/inclusiveGatewayInvalidDefaultGate.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/inclusiveGatewayWithDefaultSimulationPath.bpmn2
=> JBPM-5095: default gate tests

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/edit.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/saveplugin.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/config.js
@jlindop how to test:
1. open existing process and select part of it
2. press the "Copy to Clipboard" button in navbar (ctrl-c should work too)
3. press the "Paste" button in navbar (or ctrl-v) and it should paste as always
4. Create a new process - the paste button in navbar should be active - click it and it should paste the copied nodes)
5. Open a new tab in browser and open designer .. open existing or create new process 
6. Paste button should be enabled and you should be able to paste the copied nodes again
7. Open a new browser window and open existing or create new process
8. Paste button should be active and you should be able to paste the copied nodes again
Thanks.
=> PRODMGT-1511 - Ability to copy and paste process content across windows/packages

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/stencilsets/bpmn2.0jbpm/stencildata/bpmn2.0jbpm.orig
@jlindop to test just drag/drop a MI subprocess onto canvas and make sure the MI data input and MI data output properties are String type (not dropdowns any more).
=> JBPM-5143 - MI Subprocess mi data input and mi data output properties should be String type

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxChecker.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxCheckerTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/genericTask.bpmn2
=> JBPM-5142: added test for generic task syntax checking

jbpm-designer-backend/pom.xml, jbpm-designer-backend/src/main/java/org/jbpm/designer/validation/BPMN2FileNameValidator.java
dependent on https://github.com/uberfire/uberfire/pull/384
=> reuse ValidatioUtils from uberfire-commons-editor-backend

jbpm-designer-api/src/main/resources/org/jbpm/designer/resources/i18n/DesignerConstants.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/i18n/translation.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/i18n/translation_en.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/simulationresults.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/simulation/chartutils.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/simulation/timeline-min.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/humantaskchart.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/processchart.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/processevents.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/taskchart.jsp
Note that RHBPMS-75 has been approved to go into 6.4.x
=>  RHBPMS-75: Complete i18n of simulation tab

jbpm-designer-api/src/main/resources/org/jbpm/designer/resources/i18n/DesignerConstants.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/i18n/translation.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/i18n/translation_en.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/simulationresults.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/simulation/chartutils.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/simulation/timeline-min.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/humantaskchart.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/processchart.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/processevents.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/taskchart.jsp
Commit cherry-picked from 6.4.x branch.
=> JBPM-5132: Complete i18n of simulation tab (#296)

jbpm-designer-standalone/pom.xml
Include hibernate dependencies to fix broken build.
@tsurdilo @jlindop Please review to fix broken build...
=> GUVNOR-2600: Expose Dynamic Bean Validation through DataModelOracle

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshaller.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/callActivityInSubprocess.bpmn2
=> JBPM-5190: constant assignments fixed for call activity

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxChecker.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/SyntaxCheckerErrors.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/utils/Bpmn2Loader.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxCheckerTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/test/bpmn2/Bpmn2UnmarshallingTestCase.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/userTaskWithTaskName.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/userTaskWithoutTaskName.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/test/bpmn2/userTask.json
Please, merge #334 at first. After needed PR will be merged, I will amend appropriately this PR.
=> JBPM-5090: tests for checking taskName added

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshaller.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxCheckerTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/errorBoundaryEvent.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/errorBoundaryEventMissingDefinition.bpmn2
=> JBPM-5134: Added tests for error boundary events (#273)

jbpm-designer-standalone/pom.xml, jbpm-designer-standalone/src/main/resources/org/jbpm/designer/jBPMDesigner.gwt.xml
depends on https://github.com/droolsjbpm/kie-wb-common/pull/406
=> JBPM-5071 - remove of jbpm runtime from workbench

jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/test/bpmn2/Bpmn2UnmarshallingTestCase.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/receiveTask.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/sendTask.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/subprocessTaskAssignments.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/subprocessTaskAssignments.json, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/businessRule.bpmn2
=> JBPM-5138: tests for EndEvent input assignments

jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java
This PR updates the usage of PopUps in order to call the new PopUps API (that implements the MVP pattern using Errai UI).
See:
- https://issues.jboss.org/browse/GUVNOR-2431
- https://github.com/uberfire/uberfire/pull/443
=> GUVNOR-2431: Redesign Copy, Save, Rename, Restore and Delete Popups (away from FormStylePopup)

jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditor.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditorView.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditorViewImpl.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditorWidget.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditorWidgetViewImpl.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/ActivityDataIOEditorTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/ActivityDataIOEditorViewImplTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/ActivityDataIOEditorWidgetTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/ActivityDataIOEditorWidgetViewImplTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetViewImplTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/shared/util/StringUtilsTest.java
=> JBPM-5152: added tests for assignments editor

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/edit.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/saveplugin.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/config.js
Cherry-pick to 6.5.x branch (this is already on master for a while now). 
See https://issues.jboss.org/browse/BPMSPL-289 for request to cherry-pick to 6.5.x
=> [6.5.x] PRODMGT-1511 - Ability to copy and paste process content across windows/packages (#257)

jbpm-designer-backend/src/test/java/org/jbpm/designer/server/BusinessProcessCopyHelperTest.java
=> [6.5.x] RHBPMS-4164 - org.jbpm.designer.server.BusinessProcessCopyHelperTest fails on Windows

jbpm-designer-backend/src/test/java/org/jbpm/designer/server/BusinessProcessCopyHelperTest.java
=> [Master] RHBPMS-4164 - org.jbpm.designer.server.BusinessProcessCopyHelperTest fails on Windows

jbpm-designer-backend/src/test/java/org/jbpm/designer/server/BusinessProcessCopyHelperTest.java
=> [6.4.x] RHBPMS-4164 - org.jbpm.designer.server.BusinessProcessCopyHelperTest fails on Windows

jbpm-designer-standalone/pom.xml
Needs:
droolsjbpm/droolsjbpm-build-bootstrap#250
errai/errai#184
uberfire/uberfire#461
=> Upgrade to GWT 2.8.0-rc1

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/servicerepo.js
=> JBPM-5251: duplicities not cached more

jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditorViewImpl.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetViewImpl.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/shared/util/StringUtils.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/util/ComboBox.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/util/ComboBoxView.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/util/ListBoxValues.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetViewImplTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/util/ComboBoxTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/util/ListBoxValuesTest.java
For a description of how this is fixed in the UI, see
https://issues.jboss.org/browse/RHBPMS-4202?focusedCommentId=13290456&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13290456
=> RHBPMS-4202: Allow long constants in DataInput assignments

jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/ProcessInfoServlet.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/ProcessInfoServletTest.java, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/propertywindow.js
Fixed by making the call from propertywindow.js to the ProcessInfo servlet asynchronous.
=> RHBPMS-519: Fix problem selecting gateway in BP

jbpm-designer-api/src/main/java/org/jbpm/designer/service/DesignerAssetService.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshaller.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonUnmarshaller.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/server/service/DefaultDesignerAssetService.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2UnmarshallingTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/server/service/DefaultDesignerAssetServiceTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/customProperties.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/customProperties.json, jbpm-designer-client/pom.xml, jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandler.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants.java, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/stencilsets/bpmn2.0jbpm/stencildata/bpmn2.0jbpm.orig
@tsurdilo @jomarko could you please have a look?
=> JBPM-5354 - Support case definition as new resource type in authoring

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxChecker.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/SyntaxCheckerErrors.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxCheckerTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/multipleSubprocessStartEvents.bpmn2
=> [6.5.x] JBPM-5347: multiple start events of sub-processes validated

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/servicerepo.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/simulationresults.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/simulation/timeline-min.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/humantaskchart.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/taskchart.jsp
@hasys fixes the issues you reported on https://issues.jboss.org/browse/RHBPMS-4131
=> RHBPMS-4130 - break possible script tag

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/servicerepo.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/simulationresults.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/simulation/timeline-min.js, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/humantaskchart.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/simulation/taskchart.jsp
@hasys fixes the issues you reported on https://issues.jboss.org/browse/RHBPMS-4131
=> [6.5.x] RHBPMS-4130 - break possible script tag

jbpm-designer-api/src/main/java/org/jbpm/designer/service/DesignerSpecific.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetViewImpl.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/util/DataIOEditorNameTextBox.java
@romartin this goes with the pr i sent to your commons fork
=> fix ambiguous resolutions between designer and stunner property editors

jbpm-designer-api/src/main/java/org/jbpm/designer/forms/BPMNFormBuilderService.java, jbpm-designer-backend/pom.xml, jbpm-designer-backend/src/main/java/org/jbpm/designer/repository/AssetTypeMapper.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/BPMNFormBuilderManager.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/TaskFormInfo.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/TaskFormTemplateManager.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderService.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/TaskFormsEditorServlet.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/TaskFormsServlet.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/TaskFormsServletTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/taskforms/builder/processForm.json, jbpm-designer-backend/src/test/resources/org/jbpm/designer/taskforms/builder/taskForm.json, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/inlinetaskformeditor.js
- Added new Form building mechanism
- Added BPMNKieWorkbenchFormBuilderService as a default builder
- Modified editor to open new Form Editor instead of the old one.
=> KIE forms jBPM integration

jbpm-designer-backend/src/main/java/org/jbpm/designer/server/indexing/bpmn2/DesignerProcessDataEventListener.java
@tsurdilo @jlindop @krisv here is fix for the simulation errors in tests.
=> [DROOLS-1353] contextual conversation - fix for simulation

jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2UnmarshallingTest.java
=> RHBPMS-4483: tests for presence of MILoopCharacteristics

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/propertywindow.js
Should be "Workflow Patterns ...."
@jlindop you can test the "Synchronizing Merge" pattern as that one was for sure breaking things.
=> [6.5.x] RHBPMS-4541 - Workflow with gateway is corrupting a Business Process

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/propertywindow.js
Should be "Workflow Patterns ...."
@jlindop you can test the "Synchronizing Merge" pattern as that one was for sure breaking things.
=> RHBPMS-4541 - Workflow with gateway is corrupting a Business Process

jbpm-designer-distribution-wars/pom.xml, jbpm-designer-distribution-wars/src/main/assembly/assembly-standalone-tomcat-7_0.xml
Please don't merge yet. All the IP BOM 7.0.0.CR5 PRs need to be merged together.
=> Fixes after JPA 2.0 to 2.1 upgrade

jbpm-designer-standalone/pom.xml
Preference API changed, so I needed to make some minor changes here.
Dependes on: https://github.com/uberfire/uberfire/pull/605
=> UF-459: Preferences API Refactor

jbpm-designer-standalone/pom.xml, jbpm-designer-standalone/src/main/java/org/jbpm/designer/client/navbar/AppNavBar.html, jbpm-designer-standalone/src/main/java/org/jbpm/designer/client/navbar/AppNavBar.java
Depends on uberfire/uberfire#573
I'm getting an non related error when I try to run the WB:
https://gist.github.com/ederign/ccdbb182eaad66870af90222f7cedd47
=> [UF-443] - Header and Footer should support Errai UI

jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandler.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewProcessHandler.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandlerTest.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/handlers/NewProcessHandlerTest.java, jbpm-designer-standalone/pom.xml
* The creation of new resources must be observed by the Library perspective.
=> GUVNOR-2851, GUVNOR-2870, GUVNOR-2835: Library perspective

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/BpmnMarshallerHelper.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshaller.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonUnmarshaller.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxChecker.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/validation/SyntaxCheckerErrors.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2UnmarshallingTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/validation/BPMN2SyntaxCheckerTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/dmnBusinessRule.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/dmnBusinessRule.json, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/dmnBusinessRule.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/validation/emptyDmnBusinessRule.bpmn2, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/stencilsets/bpmn2.0jbpm/stencildata/bpmn2.0jbpm.orig
depends on https://github.com/droolsjbpm/jbpm/pull/746
@tsurdilo do you mind having a quick look?
@etirelli this allows now to use DMN as rule language in designer
=> JBPM-5681 - DMN support for BusinessRuleTask

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshaller.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonUnmarshaller.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2UnmarshallingTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/callActivityAbortParent.bpmn2, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/callActivityAbortParent.json, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/stencilsets/bpmn2.0jbpm/stencildata/bpmn2.0jbpm.orig
depends on https://github.com/droolsjbpm/jbpm/pull/749
=> JBPM-5460 - event subprocess - configurable abort propagation

jbpm-designer-backend/pom.xml, jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderService.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java
This PR adapts the testing to a code change introduced in https://github.com/kiegroup/kie-wb-common/pull/771
@jlindop @tsurdilo  can you take a look?
Comment merge with:
https://github.com/kiegroup/kie-wb-common/pull/771
https://github.com/kiegroup/jbpm-wb/pull/680
=> JBPM-5738: Add default configuration for fields that nest forms.

jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandler.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewProcessHandler.java
Cherry picked from master (https://github.com/kiegroup/jbpm-designer/pull/571)
=> [7.0.x] GUVNOR-3001: [Library] Business Process asset icon is empty

jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerViewImpl.java, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/editor.st, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/view.js
@jlindop this fixes the issue you saw sometimes where the designer frame does not resize after full screen is enabled.
=> RHBPMS-4704 - fix to ask for view to resize after full screen mode

jbpm-designer-backend/src/main/java/org/jbpm/designer/server/indexing/BPMN2FileIndexer.java
Please do not merge yet.
https://github.com/kiegroup/kie-wb-common/pull/811
https://github.com/kiegroup/jbpm-designer/pull/581
https://github.com/kiegroup/drools-wb/pull/465
=> GUVNOR-2787 : [Library] Use Lucene to list assets in the project page

jbpm-designer-backend/src/main/java/org/jbpm/designer/server/indexing/BPMN2FileIndexer.java
This is the corollary of https://github.com/kiegroup/jbpm-designer/pull/581 for 7.0.x
(cherry picked from commit 75dffde957b9b054af6c45334dff8f6bdc6f5a53)
=> [7.0.x] GUVNOR-2787: [Library] Use Lucene to list assets in the project page

jbpm-designer-api/src/main/resources/org/jbpm/designer/resources/i18n/DesignerConstants.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/editor.st, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/i18n/translation.jsp, jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/view.js
this also fixed JBPM-5986
the full-screen button in jbpm-designer is now a toggle button. when in full screen mode user can press it again to exit out of it
=> JBPM-5988 - Designer have no button to exit from full screen

jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/propertywindow.js
@hasys let me know if this is better now. thanks.
=> JBPM-5983 - Remove button for Process Variables is hidden

jbpm-designer-client/src/main/java/org/jbpm/designer/client/notification/DesignerNotificationPopupsManager.java
Correctly displays the notification now
=> JBPM-5984 - Workbench notify twice about broken Process

jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java
See https://issues.jboss.org/browse/JBPM-6069
=> JBPM-6069: Missing CRUD buttons in asset editors

jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderService.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java
Reverts kiegroup/jbpm-designer#627
Should not have been merged yet as it's part of an ensemble.
=> Revert "JBPM-5736, JBPM-5985, JBPM-5723 & JBPM-5911 Form synchronization when model changes"

jbpm-designer-backend/pom.xml
=> [7.3.x] JBPM-6310 - update to jbpm-workitems module (#648)

jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshaller.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java, jbpm-designer-backend/src/test/resources/org/jbpm/designer/bpmn2/impl/onEntryonExitActionsEscaping.bpmn2
6.5.x port needed for RHBPMS-4865
=> [6.5.x] JBPM-5437: Escape quotes inside of entry/exit actions (#515)

jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/DesignerPresenterTest.java
Cherry-picked from [master](https://github.com/kiegroup/jbpm-designer/pull/683).
=> [7.4.x] RHBPMS-5008: [Security management] Disabled assets can be edited (#683)

jbpm-designer-backend/src/main/java/org/jbpm/designer/repository/vfs/VFSRepository.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnit.java
JGITFS support for multiple and scalable FS
(prerequisite for workspaces and cloud)
Also:
[AF-573] Refactoring in order to centralize FileSystem Calls
[AF-569] Cleanup and simplify clustering
depends on: https://github.com/AppFormer/uberfire/pull/881
=> [BPMSPL-744] GIT related enhancements for scalable workspaces

jbpm-designer-api/src/main/java/org/jbpm/designer/type/Bpmn2TypeDefinition.java
Related Issues:
https://github.com/kiegroup/appformer/pull/116
https://github.com/kiegroup/kie-wb-common/pull/1317
https://github.com/kiegroup/drools-wb/pull/727
https://github.com/kiegroup/jbpm-designer/pull/728
=> [AF-913]: Changed category to BPMN Type Definition.

jbpm-designer-api/src/main/java/org/jbpm/designer/type/Bpmn2TypeDefinition.java
Reverts kiegroup/jbpm-designer#728
=> Revert "[AF-913]: Changed category to BPMN Type Definition."

jbpm-designer-backend/src/main/java/org/jbpm/designer/query/DesignerFindDataTypesQuery.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/query/DesignerFindRuleFlowNamesQuery.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/repository/vfs/RepositoryDescriptor.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/repository/vfs/RepositoryDescriptorProvider.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/repository/vfs/VFSRepository.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/server/indexing/BPMN2FileIndexer.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnit.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/CalledElementServlet.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/JbpmServiceRepositoryServlet.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/ServiceRepoUtils.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/VFSRepositoryGitFileSystemTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/server/indexing/BPMN2FileIndexerIndexingTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/server/indexing/TestBPMN2FileIndexer.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnitVFSGitTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnitVFSTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/CalledElementServletTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/ServiceRepoUtilsTest.java, jbpm-designer-client/pom.xml, jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandler.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/DesignerPresenterTest.java
fix for NPE on project creation
Fixes add project
Remove WorkspaceProjectContext from backend. Pass space as parameter.
=> AF-648 : Change Project from a folder in a repo to a repository

jbpm-designer-api/pom.xml, jbpm-designer-api/src/main/java/org/jbpm/designer/type/Bpmn2TypeDefinition.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewProcessHandler.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/type/Bpmn2Type.java
https://github.com/kiegroup/appformer/pull/116
https://github.com/kiegroup/kie-wb-common/pull/1317
https://github.com/kiegroup/drools-wb/pull/727
https://github.com/kiegroup/jbpm-designer/pull/732
https://github.com/kiegroup/kie-wb-distributions/pull/664
=> [AF-913]: Changed category to BPMN Type Definition

jbpm-designer-backend/src/main/java/org/jbpm/designer/repository/vfs/RepositoryDescriptorProvider.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/profile/impl/JbpmProfileImpl.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/vfs/RepositoryDescriptorProviderTest.java
AF-1065: [Project Oriented] Unable to create new Process or Case Definition in the second project
AF-1061: [Project Oriented] Error dialog when creating Business process in new project after creating other project
=> AF-1065 and AF-1061: New Process errors

jbpm-designer-api/src/main/java/org/jbpm/designer/type/Bpmn2TypeDefinition.java
Related to:
https://github.com/kiegroup/appformer/pull/269
https://github.com/kiegroup/kie-wb-common/pull/1550
https://github.com/kiegroup/drools-wb/pull/838
https://github.com/kiegroup/optaplanner-wb/pull/269
https://github.com/kiegroup/jbpm-designer/pull/760
=> [AF-1087]: Added VisibleAsset Qualifier to ResourceTypeDefinitions

jbpm-designer-backend/src/main/java/org/jbpm/designer/repository/vfs/RepositoryDescriptorProvider.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/server/indexing/BPMN2FileIndexer.java, jbpm-designer-backend/src/main/java/org/jbpm/designer/web/profile/impl/JbpmProfileImpl.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/vfs/RepositoryDescriptorProviderTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnitVFSTest.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/type/Bpmn2Type.java
Ensemble together with:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/726
- https://github.com/kiegroup/kie-wb-common/pull/1546
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/301
- https://github.com/kiegroup/drools-wb/pull/840
=> BAQE-400: Remove unused imports

jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerView.java, jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerViewImpl.java
Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/293
* https://github.com/kiegroup/kie-wb-common/pull/1628
* https://github.com/kiegroup/drools-wb/pull/850
* https://github.com/kiegroup/jbpm-designer/pull/768
=> AF-1097: [Project Oriented] Endless asset loading appears when discarding unsaved data

jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_de.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_es.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_fr.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_ja.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_pt_BR.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_zh_CN.properties
Backport of https://github.com/kiegroup/jbpm-designer/pull/780
@tsurdilo could you please review?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/1759
https://github.com/kiegroup/jbpm-designer/pull/781
https://github.com/kiegroup/kie-wb-distributions/pull/746
=> [7.7.x] JBPM-7148: [Workbench] Enable and make Stunner the default process editor

jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_de.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_es.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_fr.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_ja.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_pt_BR.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_zh_CN.properties
@tsurdilo  could you please review?
This is part of an ensemble merge with:
https://github.com/kiegroup/kie-wb-common/pull/1758
https://github.com/kiegroup/jbpm-designer/pull/780
https://github.com/kiegroup/kie-wb-distributions/pull/747
=> JBPM-7148: [Workbench] Enable and make Stunner the default process editor

jbpm-designer-backend/pom.xml, jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/VFSRepositoryDefaultFileSystemTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/VFSRepositoryGitFileSystemTest.java
https://github.com/kiegroup/jbpm-designer/pull/808
https://github.com/kiegroup/kie-wb-common/pull/2023
https://github.com/kiegroup/drools-wb/pull/908
=> BAQE-488: Add tests for creating asset which already exists

jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java
https://issues.jboss.org/browse/DROOLS-3425
https://github.com/kiegroup/kie-wb-common/pull/2503
https://github.com/kiegroup/drools-wb/pull/1082
https://github.com/kiegroup/jbpm-designer/pull/837
https://github.com/kiegroup/jbpm-wb/pull/1309
https://github.com/kiegroup/optaplanner-wb/pull/327
=> DROOLS-3425 : Unexpected behavior of docks when multiple editors are opened

jbpm-designer-client/pom.xml, jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java, jbpm-designer-client/src/test/java/org/jbpm/designer/client/DesignerPresenterTest.java
Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/665
* https://github.com/kiegroup/kie-wb-common/pull/2538
* https://github.com/kiegroup/drools-wb/pull/1095
* https://github.com/kiegroup/jbpm-designer/pull/843
* https://github.com/kiegroup/jbpm-wb/pull/1319
* https://github.com/kiegroup/optaplanner-wb/pull/330
=> AF-1674: Role-based access to branches in the Workbench

jbpm-designer-api/src/main/resources/org/jbpm/designer/resources/i18n/DesignerConstants_es.properties, jbpm-designer-api/src/main/resources/org/jbpm/designer/resources/i18n/DesignerConstants_fr.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_es.properties, jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants_fr.properties
missing French and Spanish translations for 7.33, cherry-picked from master
=> Missing languages 7.33.x

.github/workflows/pull_request.yml
Adding Github Actions cleanup for disk build node to not fail like in #906
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>
=> added cleanup steps into GA workflow

jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/vfs/RepositoryDescriptorProviderTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/vfs/RepositoryDescriptorTest.java, jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/ServiceRepoUtilsTest.java
* Changed restrictive terms with low impact
**JIRA**: 
[AF-2836](https://issues.redhat.com/browse/AF-2836)
[AF-2829](https://issues.redhat.com/browse/AF-2829)
**referenced Pull Requests**: 
* https://github.com/kiegroup/kie-soup/pull/219
* https://github.com/kiegroup/appformer/pull/1178
* https://github.com/kiegroup/kie-wb-common/pull/3665
* https://github.com/kiegroup/drools-wb/pull/1509
* https://github.com/kiegroup/kie-wb-playground/pull/117
* https://github.com/kiegroup/optaplanner-wb/pull/401
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1708
* https://github.com/kiegroup/jbpm-wb/pull/1509
* https://github.com/kiegroup/kie-wb-distributions/pull/1118
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* <b>a pull request</b> please add …
=> [DO NOT MERGE] AF-2836 : Conscious language initiative jbpm-designer

jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/menu/MenuServlet.java
…
**Thank you for submitting this pull request**
**AF-2923**: https://issues.redhat.com/browse/AF-2923
[link](https://www.example.com)
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
https://github.com/kiegroup/appformer/pull/1221
<details>
<summary>
How to replicate CI configuration locally?
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository. …
=> AF-2923 :Use SAXBuilder from jdom library only with not expanding Entitites
