- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/propertywindow.js
This commit should enable the searching by content for the Defined Class Name in Imports Editor.
> BZ1166209 - Data object show list does not allow a package filtering

- jbpm-designer-standalone/pom.xml
Needed to fix a failing build, as the original 1g is not enough anymore.
> Increase memory for GWT compiler to 2g in full profile

- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Core/main.js
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/saveplugin.js
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/DesignerPresenterTest.java
The use-cases in Comments 10 & 11 of https://bugzilla.redhat.com/show_bug.cgi?id=1269969 should both not be reproducible any more. (On master, the use-case in comment 10 worked even before this PR).
The case in Comment 11 cannot be reproduced any more because when the user selects a previous version in the Overview tab, the version is opened in read-only mode (whereas previously it was editable).
This PR also fixes the problem where if you select a previous version of a BP, then hit "Restore", the "Restore" button didn't change back to "Save".
@Tiho - testing this PR should include testing that the locking functionality works when two different users have the same BP open.
> BZ1269969: Fix restore BP functionality

- jbpm-designer-backend/src/test/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshallerTest.java
When trying to run test Bpmn2JsonMarshallerTest on jdk 1.6, the test doesn't compile. I didn't create JIRA for this, because it is only a minor test fix. 
- Fixed usage of method from Files available only on JDK 7+ - replaced with method from Apache IO utils.
> Bpmn2JsonMarshallerTest - fix test compilation on JDK 1.6.

- jbpm-designer-backend/src/main/java/org/jbpm/designer/server/EditorHandler.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/editorhandler/EditorHandlerBaseTest.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/helper/TestServletConfig.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/helper/TestServletContext.java
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/editor.st
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/processdoc/default.jsp
in the process documentation tab the "PDF" button is now disabled by default. To enabled it use startup parameter:
./standalone.sh -Ddesigner.showpdfdoc=true
> JBPM-4979 - Generated PDF is unreadable - update: pdf generation enabled via system property

- jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/SimulationServletTest.java
- Fixed testLocalizedStartEndTime test.
I tried changing the language, but didn't find any that match the needs of this test (non latin, not changing months on different JDKs)
> JBPM-5153 SimulationServletTest.testLocalizedStartEndTime fails on some JDKs

- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/simulation.js
Note: RHBPMS-4011 has the flags for release in 6.3.1.
To test, I do a mvn -Dfull build of jbpm-designer, and a mvn -Dfull build of kie-wb-distributions/kie-wb (which takes a while), then run the kie-wb-6.4.1-SNAPSHOT-eap6_4.war in EAP and test from IE11 on Windows 7.
> RHBPMS-4011: Fix i18n Simulation problem in IE11

- jbpm-designer-backend/pom.xml
- jbpm-designer-distribution-wars/pom.xml
- jbpm-designer-distribution-wars/src/main/assembly/assembly-standalone-tomcat-7_0.xml
Part of an ensemble:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/226
https://github.com/droolsjbpm/drools/pull/815
https://github.com/droolsjbpm/optaplanner/pull/200
https://github.com/droolsjbpm/jbpm/pull/487
https://github.com/droolsjbpm/droolsjbpm-integration/pull/509
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/29
https://github.com/droolsjbpm/guvnor/pull/328
https://github.com/droolsjbpm/drools-wb/pull/209
https://github.com/droolsjbpm/jbpm-designer/pull/302
https://github.com/droolsjbpm/jbpm-console-ng/pull/432
https://github.com/droolsjbpm/kie-wb-distributions/pull/303
> [DROOLS-1216] exclude commons-logging and use jcl-over-slf4j instead

- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/view.js
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/config.js
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/documentation/docstructure.js
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/processdoc/default.jsp
@jlindop JS changes only . Adds a "View in Model" button for each element of the documentation. When clicked switches the tab to Process Model and selects that particular element for user.
see http://imgur.com/rWSHHXq
> JBPM-5210 - Link each element in Process Documentation to the actual element in the Process Model

- jbpm-designer-backend/src/main/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnit.java
- jbpm-designer-backend/src/main/java/org/jbpm/designer/web/server/ServiceRepoUtils.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/editorhandler/EditorHandlerBaseTest.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnitVFSTest.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/JbpmServiceRepositoryServletTest.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/web/server/ServiceRepoUtilsTest.java
- jbpm-designer-backend/src/test/resources/org/jbpm/designer/web/server/servicerepo/MicrosoftAcademy/MicrosoftAcademy.wid
- jbpm-designer-backend/src/test/resources/org/jbpm/designer/web/server/servicerepo/Minimalistic/Minimalistic.wid
- jbpm-designer-backend/src/test/resources/org/jbpm/designer/web/server/servicerepo/Rewardsystem/Rewardsystem.wid
- jbpm-designer-backend/src/test/resources/org/jbpm/designer/web/server/servicerepo/SwitchYardService/SwitchYardService.wid
- jbpm-designer-backend/src/test/resources/org/jbpm/designer/web/server/servicerepo/index.conf
This PR adds tests for automatic WID import feature.
Next 3 main changes of this PR are:
1. Injection of services needed to change pom.xml and DD was moved to lower level in the architecture. As consequence of this some interfaces are now more simple.
2. There is added try-catch block in the JbpmPreprocessingUnit class. This try-catch block ensures that installation of WIDs will continue even if the installation of some WID failed.
3. There is replaced method `deleteAsset` with the method `deleteAssetFromPath`. The method `deleteAsset` was not working and was returning `false` as information about not successful deletion. As consequence of the method replacement, the user will not more see the message, that the WorkItem is already installed. Instead of this the old *.wid file will be …
> [6.5.x] JBPM-5278: added tests and refactoring done

- jbpm-designer-standalone/pom.xml
* the project should sucessfullly compile
on a machine with 8GB RAM (even that can be
seen as quite a lot). Running 4 parallel
workers on 8GB resulted in OOMEs.
> Decrease the number of GWT workers

- jbpm-designer-backend/src/main/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnit.java
- Substituted use of IOUtils.closeQuietly with scanner.close() so it works on JDK 1.6. 
No master PR, because jdk 1.6 currently not relevant there.
> JBPM-5315 RHBPMS-4251 Removed usage of IOUtils.closeQuietly when closing Scanner instance.

- jbpm-designer-standalone/pom.xml
- jbpm-designer-standalone/src/main/resources/org/jbpm/designer/jBPMDesigner.gwt.xml
The compilation and gwt build was fixed, but when `mvn clean gwt:run` is runned, I get this error: https://gist.github.com/paulovmr/46ec2d3b12bf0f4457df6ad51fdfb4f5
Can anyone take a look at that? Opening the PR anyway, because this fixes the build.
> Webapp fix after inclusion of kie-wb-common-library

- jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewProcessHandler.java
GUVNOR-2952: [Library] Breadcrumb should be updated when the opened project is renamed
GUVNOR-2947: [Library] Fix create new asset dropdown overflow and order items alphabetically
GUVNOR-2946: [Library] Show business process, guided decision table, data object first at the empty project screen (and order the rest alphabetically).
GUVNOR-2951: [Library] Add option to create new folder/package in a project.
> Library issues fix

- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/inlinetaskformeditor.js
fixes issue so that the "cancel" button in form generation options actually aborts the operation
> JBPM-5925 - fix for cancel button in form generation

- jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshaller.java
- jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonUnmarshaller.java
- jbpm-designer-backend/src/main/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnit.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/web/preprocessing/impl/JbpmPreprocessingUnitVFSGitTest.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditor.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditorView.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditorViewImpl.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/ActivityDataIOEditorWidget.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetView.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetViewImpl.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/shared/AssignmentData.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/shared/AssignmentDataMarshaller.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/util/ListBoxValues.java
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/dataioeditor.js
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/propertywindow.js
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/stencilsets/bpmn2.0jbpm/stencildata/bpmn2.0jbpm.orig
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/ActivityDataIOEditorTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/ActivityDataIOEditorViewImplTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/ActivityDataIOEditorWidgetTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/popup/AssignmentListItemWidgetTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/shared/AssignmentDataMarshallerTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/shared/AssignmentDataTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/util/ListBoxValuesTest.java
data i/o editor shows when customEditor is set to true in wid
data i/o editor contains and maintains the values of propertyValue entries for workitem data inputs (defined in the wid)
(testing propertyValue entries with comma-separated strings only - JBPM-5975 should bring the enum functionality solution in workbench - in tests this already works)
> JBPM-5953 - Add support for predefined values to Data I/O editor

- jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderService.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java
JBPM-5736: Update taskforms component menu on task/process change.
JBPM-5985: Forms are generated incorrectly after a removal of the process/task variable.
JBPM-5723: If you delete a data field, there is no response in the form connected to it.
JBPM-5911: DatePicker should be created from LocalDate, LocalDateTime and OffsetDateTime data types.
@jsoltes @tsurdilo could you take a look?
Relates to:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/465
https://github.com/kiegroup/kie-wb-common/pull/946
https://github.com/kiegroup/jbpm-designer/pull/627
https://github.com/kiegroup/jbpm-wb/pull/778
https://github.com/kiegroup/kie-wb-distributions/pull/543
> JBPM-5736, JBPM-5985, JBPM-5723 & JBPM-5911 Form synchronization when model changes

- jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderService.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java
[Reopening](https://github.com/kiegroup/jbpm-designer/pull/627) again, this PR is part of an ensemble please don't merge until the others PR's are merged too.
JBPM-5736: Update taskforms component menu on task/process change.
JBPM-5985: Forms are generated incorrectly after a removal of the process/task variable.
JBPM-5723: If you delete a data field, there is no response in the form connected to it.
JBPM-5911: DatePicker should be created from LocalDate, LocalDateTime and OffsetDateTime data types.
@jsoltes @tsurdilo could you take a look?
Relates to:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/465
https://github.com/kiegroup/kie-wb-common/pull/946
https://github.com/kiegroup/jbpm-designer/pull/633
https://github.com/kiegroup/jbpm-wb/pull/778 …
> JBPM-5736: Update taskforms component menu on task/process change.

- jbpm-designer-backend/pom.xml
This requires some more updated to droolsjbpm-build-bootstrap that @mbiarnes  will do.
> [6.5.x] JBPM-6274 - Update batik to 1.9 for 6.5.x

- jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java
Copy of https://github.com/kiegroup/jbpm-designer/pull/665
@tsurdilo could you please review?
This is part of an ensemble, merge with:
https://github.com/kiegroup/kie-wb-common/pull/1187
https://github.com/kiegroup/jbpm-designer/pull/666
https://github.com/kiegroup/jbpm-wb/pull/904
> [7.3.x] JBPM-6409: In taskforms data inputs (if different than outpus) should be readonly by default. (Also fixes JBPM-5742)

- jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java
@tsurdilo could you please review?
This is part of an ensemble, merge with:
https://github.com/kiegroup/kie-wb-common/pull/1186
https://github.com/kiegroup/jbpm-designer/pull/665
https://github.com/kiegroup/jbpm-wb/pull/903
> [8.0.x] JBPM-6409: In taskforms data inputs (if different than outpus) should be readonly by default. (Also fixes JBPM-5742) 

- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/processdoc/default.jsp
> Fix typo in Process Documentation.

- jbpm-designer-backend/pom.xml
avalon-framework is unused dependency declared (only in) jbpm-designer-backend. It's a project that is no longer maintained since 2004. I'm deleting it to remove useless jar from final kie-wb.war
> Remove unused avalon-framework dependency

- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerView.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerViewImpl.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerWidgetPresenter.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerWidgetView.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants.java
- jbpm-designer-client/src/main/resources/org/jbpm/designer/client/resources/i18n/DesignerEditorConstants.properties
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/saveplugin.js
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/config.js
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/DesignerPresenterTest.java
See:
- https://issues.jboss.org/browse/RHBA-148
- https://issues.jboss.org/browse/AF-819
---
Demo:
---
Important topics:
I) I'm keeping the editors, that have their own implementation of the save-and-rename operation, intact;
II) I couldn't apply the generic approach on `jbpm-designer`, due to the save operation that is coupled to native JS code. Thus, I needed to implement a custom solution there;
III) The "save commit" and the "rename commit" are not being squashed. I don't think that it's a problem since we're showing explicitly to the user that two operations are being executed (but, maybe I'm missing something, wdyt @manstis?).
---
Part of an ensemble:
- https://github.com/kiegroup/appformer/pull/170
- https://github.com/kiegroup/kie-wb-common/pull/1414
- …
> AF-819: Renaming assets discards changes

- jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandler.java
This is part of an ensemble:
- kiegroup/kie-wb-common#1278 
- kiegroup/drools-wb#815
- #748
> DROOLS-2109: Show Extension labels in the new resource dialogue

- jbpm-designer-backend/pom.xml
- jbpm-designer-backend/src/main/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderService.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java
There has been some packages changes.
@tsurdilo could you please review?
This PR is part of an ensemble, merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/720
https://github.com/kiegroup/kie-wb-common/pull/1492
https://github.com/kiegroup/jbpm-designer/pull/754
https://github.com/kiegroup/jbpm-wb/pull/993
https://github.com/kiegroup/kie-wb-distributions/pull/704
> BAPL-764-migration-tool: Provide migration path from old Form Modeler to the new one

- jbpm-designer-client/pom.xml
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandler.java
- jbpm-designer-client/src/main/resources/org/jbpm/designer/jBPMDesignerClient.gwt.xml
Depends on https://github.com/kiegroup/kie-wb-common/pull/2178
With the WB consolidation we will have only one distribution which have two profiles: FULL and PLANNER AND RULES - the case definition should be only in FULL.
> AF-1512: Filtering Case Management - should be only in FULL profile

- jbpm-designer-backend/pom.xml
- jbpm-designer-client/pom.xml
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/shared/Assignment.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/shared/util/StringUtils.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/shared/AssignmentBaseTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/shared/AssignmentDataMarshallerTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/shared/AssignmentDataTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/shared/AssignmentTest.java
Hi @tsurdilo,
I fixed jbpm-designer to be able to compile it with Java 11 and fixed all tests.
*** For backend:
java.xml.bind (JAXB) - REMOVED in java 11, so I added a dependency:
`javax.xml.bind:jaxb-api`
Update: replaced by `jboss-jaxb-api_2.3_spec` see https://github.com/kiegroup/jbpm-designer/pull/833#issuecomment-464015701
*** For client:
Removed dependency to Powermock since the only way to compile it with
java 11 is upgrade version to 2. But after that a lot of test failing.
(With high probability to break a lot of tests across the entire KIE
Group projects suite).
To achieve this small refactoring incorporated.
1. Allows to mock two methods in StringUtils class (removed static)
2. Ability to replace basic StringUtils by mock in Assignments class.
Depends on …
> JBPM-8233 fixed compilation and tests for jbpm designer

- jbpm-designer-backend/pom.xml
TransformerServletTest has been [failing deterministically](http://janhrcek.cz/random-failures/#/class/org.jbpm.designer.web.server.TransformerServletTest/method/testScalePDFImage%5B1%5D) on Jenkins for the past two months.
<details>
<summary>with this exception</summary>
<pre>
java.awt.AWTError: Can't connect to X11 window server using ':34' as the value of the DISPLAY variable.
at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
at java.security.AccessController.doPrivileged(Native Method)
at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
at java.lang.Class.forName0(Native Method)
at …
> Enable java.awt.headless in tests to prevent TransformerServletTest failures on jenkins

- jbpm-designer-backend/pom.xml
- jbpm-designer-backend/src/test/java/org/jbpm/designer/taskforms/builder/BPMNKieWorkbenchFormBuilderServiceTest.java
Fixing broken tests due to some api changes.
@tomasdavidorg @tsurdilo could you please review?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/drools/pull/2277
https://github.com/kiegroup/kie-wb-common/pull/2525
https://github.com/kiegroup/jbpm-wb/pull/1316
https://github.com/kiegroup/jbpm-designer/pull/842
https://github.com/kiegroup/kie-wb-distributions/pull/898
> JBPM-6848: Form Generation fails generating forms for classes on external dependencies

- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerPresenter.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerView.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerViewImpl.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerWidgetPresenter.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/DesignerWidgetView.java
- jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/saveplugin.js
**[AF-2151](https://issues.jboss.org/browse/AF-2151) Modify asset Save button behavior and presentation**
* Depends on https://github.com/kiegroup/kie-wb-common/pull/2849
* Depends on https://github.com/kiegroup/appformer/pull/783
* Depends on https://github.com/kiegroup/drools-wb/pull/1229
> [AF-2151] Modify asset Save button behavior and presentation

- jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandler.java
- jbpm-designer-client/src/main/java/org/jbpm/designer/client/handlers/NewProcessHandler.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/handlers/NewCaseDefinitionHandlerTest.java
- jbpm-designer-client/src/test/java/org/jbpm/designer/client/handlers/NewProcessHandlerTest.java
This PR relates to both this JIRAs:
- [BAPL-1395 - Support Legacy Designer Files in Stunner](https://issues.redhat.com/browse/BAPL-1395)
- [JBPM-8124 - Remove legacy process designer from the asset list](https://issues.redhat.com/browse/JBPM-8124)
This removes the following designers from the asset creation list:
- Businnes Process (legacy)
- Case Definition (legacy)
Non-migrated files can still be opened using those legacy designers. This allows the edition, migration and removal of legacy files in a safer, more usual way.
> BAPL-1395/JBPM-8124 - Legacy Designer Files

- jbpm-designer-backend/src/test/java/org/jbpm/designer/repository/RepositoryBaseTest.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/server/BusinessProcessCopyHelperTest.java
- jbpm-designer-backend/src/test/java/org/jbpm/designer/server/service/DefaultDesignerAssetServiceTest.java
- jbpm-designer-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
* Disable JGit specific features when JGit is not the default FS
* Add a switch to choose between Monitoring and Simplified Monitoring
Simplified monitoring is the K8S FS based solution. This can't use JGit specific parts so they are disabled (Like _Pages_)
Possible values:
* -Dorg.appformer.server.simplified.monitoring.enabled=true/false
* https://github.com/kiegroup/appformer/pull/882
* https://github.com/kiegroup/kie-wb-common/pull/3128
* https://github.com/kiegroup/drools-wb/pull/1363
* https://github.com/kiegroup/jbpm-designer/pull/881
> AF-2410: default:// as main file system

- jbpm-designer-backend/pom.xml
https://issues.redhat.com/browse/JBPM-9231
There is new version of Apache Batik 1.13
Parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1395
Dependent PR kiegroup/droolsjbpm-integration#2183
> JBPM-9231: removed exlusion of batik-ext
